#!/bin/sh
#
# mk_pkg_receipt - module of the SliTaz Cook
# Copyright (C) SliTaz GNU/Linux - GNU GPL v3
#

# Receipt used for cooking the package is redundant to be included into package.
# This script will strip the original receipt to bare minimum: variables,
# {pre,post}_{install,remove} functions.

. /usr/lib/slitaz/libcook.sh

orig_receipt="$1"

# 1. Main package.
#    By default it has no dependencies.
#    You can write or omit DEPENDS="" for indicating package have no dependencies.
# 2. Split package (excluding *-dev).
#    By default every split package depends on the main package.
#    Unfortunately, in the shell script (receipt is the shell script too),
#    every undeclared variable has empty value, so there's no difference if you
#    wrote DEPENDS="" or omit it - result will be the same empty value.
#    If you want to define the split package has no dependencies - you need to
#    to put single space between the quotes: DEPENDS=" ".
# 3. Development split package.
#    Installing *-dev package should install all the files produced during
#    compilation and then were separated to the different packages, so
#    by default (if you wrote DEPENDS="" or omit it) *-dev package depends on
#    the main package and all the split packages (excluding the itself).
[ "$DEPENDS" == ' ' ] && DEPENDS='@EMPTY@'

# Receipt's signature is important, although some receipts may miss it
signature=$(head -n1 "$orig_receipt")
[ "${signature:0:1}" == '#' ] || signature='# SliTaz package receipt.'

save="$(mktemp)"
# `$(echo ...)`: normalize whitespace (space, tab, newline and their combinations and repeats)
cat > $save <<EOT
PACKAGE="$PACKAGE"; DEPENDS="$(echo $DEPENDS)"; PROVIDE="$(echo $PROVIDE)"
SUGGESTED="$(echo $SUGGESTED)"; TAZPANEL_DAEMON="$TAZPANEL_DAEMON"
TAGS="$(echo $TAGS)"; VERSION="$VERSION"; SHORT_DESC="$SHORT_DESC"
WEB_SITE="$WEB_SITE"; CATEGORY="$CATEGORY"
EOT
unset_receipt
. "$orig_receipt"
MAIN_PACKAGE="$PACKAGE"
. $save; rm $save # restore values

# Manage split packages
SPLIT=" $SPLIT "
if [ "$PACKAGE" != "$MAIN_PACKAGE"   -a   "$SPLIT" != '  ' ] &&
	echo "$SPLIT" | fgrep -q " $PACKAGE "; then
	# For packages with empty $DEPENDS
	if [ -z "$DEPENDS" ]; then
		case $PACKAGE in
			*-dev)
				# main package and all the split packages but this *-dev itself
				DEPENDS=$(echo "$MAIN_PACKAGE $SPLIT " | sed "s| $PACKAGE | |; s| *$||");;
			*)
				DEPENDS="$MAIN_PACKAGE";;
		esac
	fi

	# Default $CAT
	[ -z "$CAT" ] &&
	case $PACKAGE in
		*-dev) CAT="development|development files" ;;
	esac
fi

# Manage two-in-one $CAT="$CATEGORY|$SHORT_DESC_ADDITION"
if [ -n "$CAT" ]; then
	CATEGORY="${CAT%|*}"
	SHORT_DESC="$SHORT_DESC (${CAT#*|})"
fi

# escape quotes for receipt
SHORT_DESC="${SHORT_DESC//\"/\\\"}"

# Mandatory variables
cat <<EOF
$signature

PACKAGE="$PACKAGE"
VERSION="$VERSION"
EOF
[ -n "$EXTRAVERSION"    ] && echo "EXTRAVERSION=\"$EXTRAVERSION\""
cat <<EOF
CATEGORY="$CATEGORY"
SHORT_DESC="$SHORT_DESC"
MAINTAINER="$MAINTAINER"
LICENSE="$LICENSE"
WEB_SITE="$WEB_SITE"
EOF

# Optional variables
[ -n "$TAGS"            ] && echo "TAGS=\"$TAGS\""                 | tr -ds '\t' ' '
case "x$DEPENDS" in
	x|x@EMPTY@) ;;
	*)                       echo "DEPENDS=\"$DEPENDS\""           | tr -ds '\t' ' ';;
esac
[ -n "$PROVIDE"         ] && echo "PROVIDE=\"$PROVIDE\""           | tr -ds '\t' ' '
[ -n "$CONFIG_FILES"    ] && echo "CONFIG_FILES=\"$CONFIG_FILES\"" | tr -ds '\t' ' '
[ -n "$SUGGESTED"       ] && echo "SUGGESTED=\"$SUGGESTED\""       | tr -ds '\t' ' '
[ -n "$DATABASE_FILES"  ] && echo "DATABASE_FILES=\"$DATABASE_FILES\""
[ -n "$TAZPANEL_DAEMON" ] && echo "TAZPANEL_DAEMON=\"$TAZPANEL_DAEMON\""

# Extract {pre,post}_{install,remove} functions;
# post_install()      will be copied for both main and all the split packages
# post_install_gtk_() will be copied as post_install() for gtk+ package only
#
# restricted name (gtk+ -> gtk_; acl-dev -> acl_dev)
rname=$(echo -n $PACKAGE | tr -c 'a-zA-Z0-9' '_')
for i in pre post; do
	for j in install remove; do
		sed    "/^${i}_${j}()/,/^}/!d"        "$orig_receipt"
		sed    "/^${i}_${j}_$rname()/,/^}/!d" "$orig_receipt" \
		| sed "s|^${i}_${j}_$rname()|${i}_${j}()|"
	done
done
